;;; -*- Mode: Lisp; indent-tabs-mode: nil -*-

(cl:defpackage #:gittage
  (:use :common-lisp :alexandria :iterate :split-sequence
        :pergamum :portable-spawn :executor)
  (:export
   ;; knobs
   #:*http-proxy*
   ;; globals
   #:*repository*
   ;; conditions
   #:git-condition
   #:git-error
   #:simple-git-error
   #:repository-condition
   #:repository-error
   #:simple-repository-error
   #:fetch-error
   #:repository-not-clean-during-fetch
   #:dirt-files-in-repository
   #:empty-repository
   #:patch-failure
   ;;
   #:git
   #:with-repository
   #:defgitpredicate
   ;;
   #:init-repo
   #:nonbare-repository-present-p
   #:repository-bare-p
   #:repository-world-readable-p
   #:repository-unstaged-changes-p
   #:repository-staged-changes-p
   #:repository-changes-p
   #:repository-status
   #:update-repository-for-dumb-servers
   ;;
   #:repository-policy
   #:with-repository-policy
   #:repository-policy-value
   ;;
   #:config-var
   ;;
   #:remotes
   #:find-remote
   #:add-remote
   #:remove-remote
   #:ensure-remote
   #:fetch-remote
   ;;
   #:ref-shortp
   #:canonicalise-ref
   #:ref-headp
   #:ref-remotep
   #:make-remote-ref
   #:parse-commit-id
   #:parse-ref-value
   #:cook-ref-value
   #:ref-value
   #:ref=
   #:symbolic-reffile-value
   #:refs-by-value
   ;;
   #:get-head
   #:set-head
   #:detach-head
   #:head-detached-p
   #:with-maybe-detached-head
   ;;
   #:branches
   #:branch-present-p
   #:remove-branch
   #:set-noncurrent-branch
   #:set-branch
   #:set-branch-index-tree
   #:stash
   #:apply-stash
   #:ensure-clean-repository
   #:set-head-index-tree
   #:with-branch-change
   #:with-remote
   ;;
   #:with-repository-write-access
   ;;
   #:commit
   #:commit-id
   #:commit-author
   #:commit-date
   #:commit-message
   #:commit-log
   #:git-commit
   ;;
   #:*supported-import-types*
   #:hg #:darcs #:cvs #:svn #:tarball
   #:apply-diff
   #:locate-vcs-import-executables
   #:locate-import-executables
   #:indirect-import-mercurial
   #:indirect-import-darcs
   #:direct-import-cvs
   #:direct-import-svn
   #:direct-import-tarball
   #:indirect-import-cvs
   #:indirect-import-svn
   ;;
   #:determine-available-module-tarball-version-starting-after
   ;;
   #:touch-repository
   #:touch-rsync-repository
   #:touch-cvs-repository
   ))
